# 1) Show that a List in python can
# • store elements of different types (integer, float, string, etc.)
# • store duplicate elements

In [11]:
lst=[1,'A',"String",1.1,-2]
print(lst)

[1, 'A', 'String', 1.1, -2]


# 2) Check if an Element Exists in a List ( Note make use of ‘in’)

In [12]:
num=[1,2,3,4,5]

n=int(input("Enter a number:"))

if n in num:
    print("Element present")
else:
    print("Element not present")

Enter a number:3
Element present


In [13]:
num=[1,2,3,4,5]
n=int(input("Enter a number:"))
if n in num:
    print("Element present")
else:
    print("Element not present")

Enter a number:6
Element not present


# 3) Find the length of the list.

In [14]:
lst=[1.2,3,0,-4,'f']
print(len(lst))

5


# 4) Create a list with value n ** 2 where n is a number from 1 to 5

In [10]:
squares_list = []

for n in range(1, 6):
    squares_list.append(n ** 2)

print("List of squares from 1 to 5:")
print(squares_list)

List of squares from 1 to 5:
[1, 4, 9, 16, 25]


# 5) Python program to print the elements of an array in reverse order

In [22]:
my_array = [1, 2, 3, 4, 5]

print("Elements of the array in reverse order:")
reversed_array = my_array[::-1]
for element in reversed_array:
    print(element)

Elements of the array in reverse order:
5
4
3
2
1


# 7) Python program to sort the elements of an array in descending order

In [25]:
array=[1,4,5,7,3]
array.sort(reverse=True)
print(array)

[7, 5, 4, 3, 1]


# 8) Compare 2 lists in python(use The cmp() function
# • The set() function and == operator
# • The sort() function and == operator)

In [29]:
list1=[2,3,4,5,5,1,1]
list2=[2,3,4,5,5,1,1]
(list1.sort(reverse=False))
(list2.sort(reverse=False))
print(list1)
print(list2)
if list1==list2:
    print("Equal")
else:
    print("Not equal")
n1=set(list1)
n2=set(list2)
print(n1)
print(n2)

[1, 1, 2, 3, 4, 5, 5]
[1, 1, 2, 3, 4, 5, 5]
Equal
{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5}


In [31]:
list1 = [1, 2, 3]
list2 = [1, 2, 3, 4, 5]

if set(list1) == set(list2):
    print("The lists are equal")
else:
    print("The lists are not equal")

The lists are not equal


# 9) Remove a specific item from a list by using the three methods remove(), pop(),
# and clear().

In [32]:
lst=[1,'a',2.2,0,-9]
lst.remove(1)
lst.pop()
print(lst)
lst.clear()
print(lst)

['a', 2.2, 0]
[]


# 10) Write a NumPy program to convert an integer array to a floating type.
# ( x = np.asfarray(a))

In [33]:
import numpy as np
arr=np.array([1,2,3])
print(arr)
x=np.asfarray(arr)
print(x)

[1 2 3]
[1. 2. 3.]


# 11) Write a NumPy program to convert a list and tuple into arrays.

In [35]:
import numpy as np
lst=[1.1,2.2,3.3]
tple=(1,2,3)

x=np.array(lst)
y=np.array(tple)

print(x)
print(type(x))
print(y)

[1.1 2.2 3.3]
<class 'numpy.ndarray'>
[1 2 3]


# 12) Write a NumPy program to convert a list and tuple into arrays.(np.asarray)

In [37]:
import numpy as np
lst=[1.1,2.2,3.3]
tple=(1,2,3)

x=np.asarray(lst)
y=np.asarray(tple)

print(x)
print(type(x))
print(y)

[1.1 2.2 3.3]
<class 'numpy.ndarray'>
[1 2 3]
